import './global.css';
import { Providers } from './providers/providers';

export const metadata = {
  title: 'Welcome to vnc-auth-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="lock-position">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
