containers:
  api:
    env:
      apiDatabaseUrl: postgres://enclaveid:enclaveid@enclaveid-postgresql.default.svc.cluster.local:5432/enclaveid_api

initContainers:
  createSecrets:
    arguments:
      environment: microk8s

postgresql:
  global:
    postgresql:
      architecture: standalone
      auth:
        username: enclaveid
        password: enclaveid
  primary:
    initdb:
      scripts:
        init-api.sql: |
          CREATE DATABASE enclaveid_api;
          GRANT ALL PRIVILEGES ON DATABASE enclaveid_api TO enclaveid;
        init-guacamole.sql: |
          CREATE DATABASE enclaveid_guacamole;
          GRANT ALL PRIVILEGES ON DATABASE enclaveid_guacamole TO enclaveid;
  sidecars: [] # TODO add envoy mTLS sidecar

# We use a separate database for guacamole
guacamole:
  postgres:
    database: enclaveid_guacamole
    password: enclaveid
    port: '5432'
    user: enclaveid
    hostname: enclaveid-postgresql
  guacd:
    image:
      tag: 1.5.5
  guacamole:
    image:
      tag: 1.5.5

redis:
  architecture: standalone
  auth:
    enabled: false

dagsterCloud:
  deployment: prod
