FROM node:20.11.1-alpine3.18

RUN npm install -g pnpm@8.15.4

COPY /workspace /app

WORKDIR /app

RUN pnpm install

RUN pnpm exec nx run spa-frontend:build --configuration=development --skipTypeCheck=true

EXPOSE 4200

CMD ["pnpm", "exec", "nx", "run", "spa-frontend:serve", "--configuration=development"]
