apiVersion: v1
kind: Service
metadata:
  name: {{ include "enclaveid.fullname" . }}-guacamole-tunnel
  labels:
{{- include "enclaveid.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "enclaveid.name" . }}-guacamole-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
