// Generated by ts-to-zod
import { z } from 'zod';

export const bigFiveSchema = z.object({
  openness: z.number(),
  conscientiousness: z.number(),
  extraversion: z.number(),
  agreeableness: z.number(),
  neuroticism: z.number(),
});

// Custom type definitions
export const genericResponseSchema = {
  200: z.object({
    success: z.boolean(),
  }),
  400: z.object({
    error: z.string(),
  }),
};
