apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enclaveid.fullname" . }}
  labels:
    {{- include "enclaveid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "enclaveid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "enclaveid.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: unencrypted-shared-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-pvc
        - name: api-tmpfs
          emptyDir:
            medium: Memory
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enclaveid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: create-secrets
          image: "{{ .Values.initContainers.createSecrets.image }}"
          imagePullPolicy: {{ .Values.initContainers.createSecrets.imagePullPolicy }}
          args: [
            "{{ .Values.initContainers.createSecrets.arguments.environment }}",
            "{{ .Values.initContainers.createSecrets.arguments.keyName }}",
            "{{ .Values.initContainers.createSecrets.arguments.kvStoreName }}",
            "{{ .Values.initContainers.createSecrets.arguments.managedIdentity }}",
            "{{ .Values.initContainers.createSecrets.arguments.maaEndpoint }}",
            "{{ .Values.initContainers.createSecrets.arguments.workloadMeasurement }}"
          ]
          # TODO: how can we add this to every container?
          volumeMounts:
            - mountPath: /tmp
              name: api-tmpfs
            - mountPath: /mnt/unencrypted-shared-storage
              name: unencrypted-shared-storage
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.containers.api.image }}"
          imagePullPolicy: {{ .Values.containers.api.imagePullPolicy }}
          env:
            - name: API_DATABASE_URL
              value: {{ .Values.containers.api.env.apiDatabaseUrl }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /tmp
              name: api-tmpfs
            - mountPath: /mnt/unencrypted-shared-storage
              name: unencrypted-shared-storage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
