---
# Source: enclaveid/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enclaveid-dev
  labels:
    helm.sh/chart: enclaveid-0.0.0
    app.kubernetes.io/name: enclaveid
    app.kubernetes.io/instance: enclaveid-dev
    app.kubernetes.io/version: "dev-0.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: enclaveid/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: enclaveid-dev
  labels:
    helm.sh/chart: enclaveid-0.0.0
    app.kubernetes.io/name: enclaveid
    app.kubernetes.io/instance: enclaveid-dev
    app.kubernetes.io/version: "dev-0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: enclaveid
    app.kubernetes.io/instance: enclaveid-dev
