FROM node:20.11.1-alpine3.18

RUN npm install -g pnpm@9.0.6

COPY dist/apps/api/ /app/

WORKDIR /app

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN pnpm install --prod

ENV HOST=0.0.0.0
ENV PORT=3000

CMD [ "node", "api" ]
