on:
  push:
    branches:
      - master
    tags:
      - '*'

name: Deploy prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      ec2_host: ${{ steps.set_ip.outputs.ec2_host }}
    steps:
    - name: Start EC2 Instance
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
        aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
      shell: bash

    - name: Fetch EC2 Instance Public IP
      id: set_ip
      run: |
        IP=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
        echo "::set-output name=ec2_host::$IP"
      shell: bash

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.set_ip.outputs.ec2_host }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          git clone https://github.com/enclave-id/enclaveid
          cd enclaveid
          git checkout ${{ github.sha }}
          ./deploy.sh

    
    
