on:
  push:
    tags:
      - 'prod'

name: Deploy prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Run Makefile Target
#         env:
#           MY_SECRET: ${{ secrets.MY_SECRET }}
#         run: make helm-chart DEPLOYMENT=aks

# AZURE_SERVICE_ACCOUNT_NAME ?= workload-identity-sa
# AZURE_RESOURCE_GROUP ?= DefaultResourceGroup-EUS
# AZURE_USER_ASSIGNED_IDENTITY_NAME ?= cluster-identity
